// Copies contract ABIs from the Foundry build (../contracts/out) into src/lib/abi.ts.
// Run after `forge build` whenever a contract interface changes: npm run sync:abi
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "..", "contracts", "out");
const list = [
  ["loanManagerAbi", "LoanManager.sol/LoanManager.json"],
  ["vaultAbi", "HourglassVault.sol/HourglassVault.json"],
  ["safetyModuleAbi", "SafetyModule.sol/SafetyModule.json"],
  ["feeSplitterAbi", "FeeSplitter.sol/FeeSplitter.json"],
  ["faucetTokenAbi", "TestnetMocks.sol/FaucetToken.json"],
  ["testFeedAbi", "TestnetMocks.sol/TestFeed.json"],
];
let ts = "// Generated by scripts/sync-abi.mjs from ../contracts/out. Do not edit by hand.\n\n";
for (const [name, file] of list) {
  const { abi } = JSON.parse(readFileSync(join(out, file), "utf8"));
  ts += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
}
writeFileSync(join(root, "src", "lib", "abi.ts"), ts);
console.log("wrote src/lib/abi.ts:", list.map((l) => l[0]).join(", "));
